#!/bin/sh -ex

export DH_GOLANG_BUILDPKG="github.com/containers/podman/test/e2e"
export DH_GOLANG_INSTALL_ALL=1
export DH_VERBOSE=1

dh_auto_configure -O--buildsystem=golang -O--builddirectory=_build
dh_auto_build -O--buildsystem=golang -O--builddirectory=_build

export PODMAN_BINARY=/usr/bin/podman
export PODMAN_REMOTE_BINARY=/usr/bin/podman-remote
export QUADLET_BINARY=/usr/libexec/podman/quadlet

# bindings tests need access to podman-registry
PATH="$(pwd)/hack:${PATH}" \
dh_auto_test -O--buildsystem=golang -O--builddirectory=_build --no-parallel -- -timeout 30m

